# Generated by Django 5.2.6 on 2026-01-18 01:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_notification_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tailoringtask",
            name="commission_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Calculated commission amount",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="tailoringtask",
            name="commission_paid",
            field=models.BooleanField(
                default=False,
                help_text="Whether commission has been credited to tailor",
            ),
        ),
        migrations.AddField(
            model_name="tailoringtask",
            name="commission_paid_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tailoringtask",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Commission percentage for this task",
                max_digits=5,
            ),
        ),
        migrations.CreateModel(
            name="TailorCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original order amount",
                        max_digits=10,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission percentage applied",
                        max_digits=5,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission amount earned",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("credited", "Credited"),
                            ("paid", "Paid Out"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("garment_type", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("customer_name", models.CharField(max_length=200)),
                ("earned_date", models.DateTimeField(auto_now_add=True)),
                ("credited_date", models.DateTimeField(blank=True, null=True)),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_records",
                        to="core.order",
                    ),
                ),
                (
                    "tailor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_record",
                        to="core.tailoringtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tailor Commission",
                "verbose_name_plural": "Tailor Commissions",
                "ordering": ["-earned_date"],
                "indexes": [
                    models.Index(
                        fields=["tailor", "status"],
                        name="core_tailor_tailor__ac6ebe_idx",
                    ),
                    models.Index(
                        fields=["tailor", "-earned_date"],
                        name="core_tailor_tailor__659d42_idx",
                    ),
                ],
            },
        ),
    ]
