# Generated by Django 5.2.6 on 2026-01-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_commission_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="garmenttype",
            name="garment_category",
            field=models.CharField(
                choices=[
                    ("upper", "Upper Body"),
                    ("lower", "Lower Body"),
                    ("both", "Upper & Lower (Both)"),
                ],
                default="upper",
                help_text="Category of garment for measurement purposes",
                max_length=20,
            ),
        ),
    ]
