# Generated by Django 5.2.6 on 2026-01-19 14:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_garmenttype_garment_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_assigned", "Task Assigned"),
                    ("task_completed", "Task Completed"),
                    ("task_approved", "Task Approved"),
                    ("order_created", "Order Created"),
                    ("payment_received", "Payment Received"),
                    ("low_stock", "Low Stock Alert"),
                    ("rework_assigned", "Rework Assigned"),
                    ("rework_completed", "Rework Completed"),
                    ("general", "General"),
                ],
                default="general",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("delivered", "Delivered"),
                    ("for_adjustment", "For Adjustment/Rework"),
                    ("ready_for_reclaim", "Ready for Re-Claim"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Rework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rework_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("original_garment_type", models.CharField(max_length=200)),
                ("original_customer_name", models.CharField(max_length=200)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("fitting_issue", "Fitting Issue"),
                            ("design_change", "Design Change"),
                            ("workmanship_concern", "Workmanship Concern"),
                            ("material_issue", "Material Issue"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reason_description", models.TextField()),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("free", "Free (Shop Error)"),
                            ("paid", "Paid (Customer Requested)"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "additional_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Additional cost for paid reworks",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "fabric_meters_used",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("started_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reworks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reworks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fabric_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rework_fabric_used",
                        to="core.fabric",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reworks",
                        to="core.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rework",
                "verbose_name_plural": "Reworks",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ReworkMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_used", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "accessory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.accessory"
                    ),
                ),
                (
                    "rework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="core.rework",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rework Material",
                "verbose_name_plural": "Rework Materials",
            },
        ),
        migrations.AddIndex(
            model_name="rework",
            index=models.Index(fields=["status"], name="core_rework_status_8b29a5_idx"),
        ),
        migrations.AddIndex(
            model_name="rework",
            index=models.Index(fields=["order"], name="core_rework_order_i_55c7ae_idx"),
        ),
    ]
