# Generated by Django 5.2.6 on 2026-01-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_assigned", "Task Assigned"),
                    ("task_started", "Task Started"),
                    ("task_completed", "Task Completed"),
                    ("task_approved", "Task Approved"),
                    ("order_created", "Order Created"),
                    ("payment_received", "Payment Received"),
                    ("low_stock", "Low Stock Alert"),
                    ("rework_assigned", "Rework Assigned"),
                    ("rework_completed", "Rework Completed"),
                    ("general", "General"),
                ],
                default="general",
                max_length=30,
            ),
        ),
    ]
