# Generated by Django 5.2.6 on 2026-01-21 00:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_notification_notification_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("delivered", "Claimed"),
                    ("for_adjustment", "For Adjustment/Rework"),
                    ("ready_for_reclaim", "Ready for Re-Claim"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tailoringtask",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="Commission percentage for this task",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="tailoringtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("completed", "Awaiting Approval"),
                    ("approved", "Order Completed"),
                ],
                default="assigned",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TailorGarmentCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        help_text="Commission percentage for this tailor and garment type",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MinValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this commission rate is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "garment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tailor_commissions",
                        to="core.garmenttype",
                    ),
                ),
                (
                    "tailor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garment_commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tailor Garment Commission",
                "verbose_name_plural": "Tailor Garment Commissions",
                "indexes": [
                    models.Index(
                        fields=["tailor", "garment_type"],
                        name="core_tailor_tailor__96b18f_idx",
                    )
                ],
                "unique_together": {("tailor", "garment_type")},
            },
        ),
    ]
