# Generated by Django 5.2.6 on 2026-01-25 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_fabriccolor_fabricmaterial_alter_fabric_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fabric",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fabrics",
                to="core.fabriccolor",
            ),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fabrics",
                to="core.fabricmaterial",
            ),
        ),
    ]
